volumes:
  pg_data:
  static:
  media:
  redis_data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    entrypoint: sh entrypoint.sh
    env_file: .env
    depends_on:
      - db
    volumes:
      - media:/app/media/
      - static:/app/staticfiles/
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      PYTHONPATH: /app
    command: ["make", "start"]

  nginx:
    build: ./nginx/
    env_file: .env
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - static:/staticfiles/
      - media:/media/
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /root/generate_avatar_bot/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - backend

  redis:
    image: "redis:6.2-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning


  celery:
    build:
      context: ./backend/
    # entrypoint: sh entrypoint.sh
    env_file: .env
    command: celery -A core worker --loglevel=info
    volumes:
      - ./backend/:/app
    depends_on:
      - redis
      - db
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      PYTHONPATH: /app
    restart: always

  celery_beat:
    build:
      context: ./backend/
    # entrypoint: sh entrypoint.sh
    env_file: .env
    command: celery -A core beat --loglevel=info
    volumes:
      - ./backend/:/app
    depends_on:
      - redis
      - db
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      PYTHONPATH: /app
    restart: always
