# Generated by Django 4.2.16 on 2025-02-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0003_alter_package_options_alter_packagetype_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="name",
        ),
    ]
