# Generated by Django 4.2.16 on 2025-02-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0004_remove_package_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
