# Generated by Django 4.2.16 on 2025-02-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promptcategory",
            options={
                "verbose_name": "Категория промпта",
                "verbose_name_plural": "Категории промптов",
            },
        ),
        migrations.AlterModelOptions(
            name="promptstyle",
            options={
                "verbose_name": "Стиль промпта",
                "verbose_name_plural": "Стили промптов",
            },
        ),
    ]
