# Generated by Django 4.2.16 on 2025-02-19 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0002_alter_promptcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptstyle",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="styles",
                to="prompts.promptcategory",
            ),
        ),
    ]
