# Generated by Django 4.2.16 on 2025-03-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0010_avatar_element_name"),
        ("prompts", "0004_promptstyle_gender_promptstyle_prompt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promptstyle",
            name="gender",
        ),
        migrations.AddField(
            model_name="promptstyle",
            name="genders",
            field=models.ManyToManyField(blank=True, to="avatars.avatargender"),
        ),
    ]
