# Generated by Django 4.2.16 on 2025-02-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avatar",
            options={"verbose_name": "Аватар", "verbose_name_plural": "Аватары"},
        ),
        migrations.AlterModelOptions(
            name="avatarimage",
            options={
                "verbose_name": "Изображение аватара",
                "verbose_name_plural": "Изображения аватаров",
            },
        ),
        migrations.AddField(
            model_name="avatar",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
