# Generated by Django 4.2.16 on 2025-02-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0002_alter_avatar_options_alter_avatarimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="name",
            field=models.CharField(default="avatar", max_length=100),
        ),
    ]
