# Generated by Django 4.2.16 on 2025-02-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0003_avatar_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=490.0, max_digits=10),
                ),
            ],
        ),
    ]
