# Generated by Django 4.2.16 on 2025-02-19 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0005_photoformat_alter_avatarsettings_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarGender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=40)),
            ],
            options={
                "verbose_name": "Пол",
                "verbose_name_plural": "Пол",
            },
        ),
        migrations.AlterField(
            model_name="avatar",
            name="name",
            field=models.CharField(default="Model", max_length=100),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="avatars.avatargender",
            ),
        ),
    ]
