# Generated by Django 4.2.16 on 2025-02-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0006_avatargender_alter_avatar_name_alter_avatar_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="api_credit_cost",
            field=models.IntegerField(default=0),
        ),
    ]
