# Generated by Django 4.2.16 on 2025-03-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0007_avatar_api_credit_cost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avatar",
            old_name="model_id",
            new_name="element_id",
        ),
    ]
