# Generated by Django 4.2.16 on 2025-03-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0008_rename_model_id_avatar_element_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
