# Generated by Django 4.2.16 on 2025-03-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0009_avatar_is_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="element_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
