# Generated by Django 4.2.16 on 2025-02-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leonardo_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leonardogeneration",
            options={"verbose_name": "Генерация", "verbose_name_plural": "Генерации"},
        ),
    ]
