# Generated by Django 4.2.16 on 2025-02-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leonardo_service", "0002_alter_leonardogeneration_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="leonardogeneration",
            name="api_credit_cost",
            field=models.IntegerField(default=0),
        ),
    ]
