# Generated by Django 4.2.16 on 2025-03-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leonardo_service", "0003_leonardogeneration_api_credit_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leonardogeneration",
            name="style",
        ),
        migrations.AddField(
            model_name="leonardogeneration",
            name="guidance_scale",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="leonardogeneration",
            name="height",
            field=models.IntegerField(default=512),
        ),
        migrations.AddField(
            model_name="leonardogeneration",
            name="model_id",
            field=models.CharField(
                default="5c232a9e-9061-4777-980a-ddc8e65647c6", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="leonardogeneration",
            name="width",
            field=models.IntegerField(default=512),
        ),
    ]
