version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: aiogram_bot
    restart: always
    env_file:
      - ../.env
    volumes:
      - .:/app
    command: ["python", "main.py"]