# Generated by Django 4.2.16 on 2025-02-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_managers_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_authorized",
            field=models.BooleanField(default=False),
        ),
    ]
