# Generated by Django 4.2.16 on 2025-02-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_is_authorized"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatars_amount_available",
            field=models.IntegerField(default=1),
        ),
    ]
