# Generated by Django 4.2.16 on 2025-02-15 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_avatars_amount_available"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photo_format",
                    models.CharField(
                        choices=[
                            ("1:1", "1:1"),
                            ("3:4", "3:4"),
                            ("9:16", "9:16"),
                            ("16:9", "16:9"),
                        ],
                        default="1:1",
                        max_length=10,
                    ),
                ),
                ("avatars_amount_available", models.IntegerField(default=1)),
            ],
        ),
    ]
