# Generated by Django 4.2.16 on 2025-02-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_usersettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersettings",
            options={
                "verbose_name": "Настройки пользователя",
                "verbose_name_plural": "Настройки пользователей",
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="avatars_amount_available",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="god_mode",
            field=models.BooleanField(default=False),
        ),
    ]
